import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Creon Niftables",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative" >
        <Navbar />
        {children}
      </body>
    </html>
  );
}


//          className="bg-no-repeat bg-cover bg-center bg-[url('/assets/header-bg.png')] w-full h-[970px]">
