
import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav";


export const metadata: Metadata = {
  title: "Creon Niftables",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-satoshibold" >
        <Nav />
        {children}
      </body>
    </html>
  );
}


